"""timestamps with reviews

Revision ID: 4a74b78cdeec
Revises: 05fcc1e211c2
Create Date: 2023-09-19 21:14:07.225244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a74b78cdeec'
down_revision = '05fcc1e211c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating', 'timestamp')
    # ### end Alembic commands ###
