"""added logo_url column to establishment and made email non-unique in capture_email

Revision ID: 55cab8e7ac01
Revises: b82394073f10
Create Date: 2023-10-29 14:36:17.048242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55cab8e7ac01'
down_revision = 'b82394073f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('captured_email_email_key', 'captured_email', type_='unique')
    op.add_column('establishment', sa.Column('logo_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('establishment', 'logo_url')
    op.create_unique_constraint('captured_email_email_key', 'captured_email', ['email'])
    # ### end Alembic commands ###
