"""Added capture_email to Establishment

Revision ID: 7030023f9ba2
Revises: 71be29f4c1aa
Create Date: 2023-09-28 19:09:53.612721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7030023f9ba2'
down_revision = '71be29f4c1aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('establishment', sa.Column('capture_email', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('establishment', 'capture_email')
    # ### end Alembic commands ###
