"""public review sites column

Revision ID: 71be29f4c1aa
Revises: 4a74b78cdeec
Create Date: 2023-09-27 20:50:16.356250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text


# revision identifiers, used by Alembic.
revision = '71be29f4c1aa'
down_revision = '4a74b78cdeec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('establishment', sa.Column('publicReviewSites', postgresql.JSON(astext_type=Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('establishment', 'publicReviewSites')
    # ### end Alembic commands ###
