"""updated Interest model

Revision ID: b82394073f10
Revises: d1d575535610
Create Date: 2023-10-25 21:16:16.260435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b82394073f10'
down_revision = 'd1d575535610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interest', sa.Column('firstName', sa.String(length=120), nullable=False))
    op.add_column('interest', sa.Column('lastName', sa.String(length=120), nullable=False))
    op.add_column('interest', sa.Column('businessName', sa.String(length=250), nullable=True))
    op.add_column('interest', sa.Column('phoneNumber', sa.String(length=20), nullable=True))
    op.drop_column('interest', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interest', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('interest', 'phoneNumber')
    op.drop_column('interest', 'businessName')
    op.drop_column('interest', 'lastName')
    op.drop_column('interest', 'firstName')
    # ### end Alembic commands ###
