"""capturing establishment id of the email giver

Revision ID: d1d575535610
Revises: e15e245d07af
Create Date: 2023-09-29 22:29:58.215622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d575535610'
down_revision = 'e15e245d07af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('captured_email', sa.Column('establishment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'captured_email', 'establishment', ['establishment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'captured_email', type_='foreignkey')
    op.drop_column('captured_email', 'establishment_id')
    # ### end Alembic commands ###
